### ISSUE TITLE
Examples don't match with invert

### ISSUE THREAD

**Issue by JeroenStappie** [wkoch/Debounce#4]
With the addition of the invert, the examples with a custom delay no longer work as this has become ambiguous. When a custom delay is wanted, I guess this makes the extra parameters required? 

From one of the examples: 
```Debounce Button2(button2, 70); // Button2 debounced, custom 70ms delay.```
This now generates an error:
`call of overloaded 'Debounce(byte&, int)' is ambiguous`

This would work though:
`Debounce Button2(button2, 70, false, false);`

**Comment by wkoch** [comment]
Indeed. My mistake. I just glanced the code before accepting the pull request.

I think the new arguments should be optional.

I'll gladly accept a pull request if you have time to fix this, or I'll fix it myself in the next couple of weeks.

**Comment by wkoch** [comment]
> With the addition of the invert, the examples with a custom delay no longer work as this has become ambiguous. When a custom delay is wanted, I guess this makes the extra parameters required?
> 
> From one of the examples:
> `Debounce Button2(button2, 70); // Button2 debounced, custom 70ms delay.`
> This now generates an error:
> `call of overloaded 'Debounce(byte&, int)' is ambiguous`
> 
> This would work though:
> `Debounce Button2(button2, 70, false, false);`

Hey, I refactored the code with optional arguments among other improvements, so this issue should be fixed now (3059a02cc05b19ce3a90de79e5d8818560626d91), so I'm closing it. Feel free to test the new version and give feedback if you have the time.
