### ISSUE TITLE
Button Off Time (High) is same as delay time

### ISSUE THREAD

**Issue by saleemsadruddin** [wkoch/Debounce#5]
Debounce Button1(button1, 30000,false,false);
//if delay is 30 seconds then led will turn on  after 30 seconds but it will remain on for another 30 seconds after button is release.

**Comment by wkoch** [comment]
First of all, I updated the Library, fixed some stuff and simplified others, so please test the new version, it might have fixed your problem.

I didn't really understand the problem you're having or what you're trying to do, but I'll try to help the best I can.

**About debouncing**: When you press a button it will not go perfectly On and stay there until you release it, it actually fluctuates several times between On and Off until it settles, just like a ball falling from your hands to the floor will bounce some times until it stays in the floor. A debouncer is commonly used to eliminate those fluctuations inside buttons. The delay time is the minimum time the button must be settled at the On state to be computed. Continuing the ball metaphor, if debounced, you would no see the ball bouncing on the floor, you would only see it in your hand or on the floor if it stayed on the floor for more than the debounce time.

Judging by this, if  you use this library with High times like 30 seconds, you'll have to hold the button pressed and perfeclty steady for all that time for the Led to turn On, and then it will be Off as soon as you shake a little or release the button.
